version: "3.9"
   
services:
  nginx:
    image: nginx:1.18-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web

  web:
    build: .
    restart: always
    command: uvicorn app.server.app:app --host 0.0.0.0 --port=8000
    volumes:
      - .:/code
    ports:
      - 8000
    env_file:
      - ./.env